id: PB5AD852F
initial_creation_type: input
source_metadata:
  title: Trulshik Dongak Lingpa Series
  language: es
  description: The following texts are available in our series of texts by and about
    Trulshik Dongak Lingpa (’khrul zhig mdo sngags gling pa) alias Kunzang Tongdrol
    Dorje (kun bzang mthong grol rdo rje, 1862–1922), rediscoverer of the Yangti Nakpo
    cycle of Dzogchen teachings.
  volume:
    955f177d345e42f4b1130b6b267e2f21:
      title: Brief Offering Prayer to Gesar
      parent: Gesar
    e0e3479232844d70a26b352b179d633f:
      title: Prayer to the Successive Lives of the Great Trulshik 'Destroyer of Delusion'
      parent: Prayers
created_at: '2022-03-01T01:50:09.392208'
last_modified_at: '2022-03-01T01:50:09.392212'
